### ISSUE TITLE
Postgres store enhancement

### ISSUE THREAD

**Issue by Ganitzsh** [inklabs/rangedb#6]
I will put a list of all the things I noticed on the Postgres store and that should be changed. I will then start working on that ASAP, create a branch and link a PR to this issue.

- [x] Add proper error handling

- [x] Create indexes and constraints for the table

- [ ] Reduce the number of simultaneous connections

- [x] Handle transactions

**Comment by pdt256** [comment]
Transactions were added in #5 
Error handling was added in #8

**Comment by pdt256** [comment]
Indexes were added in https://github.com/inklabs/rangedb/commit/34d3765507c832b31b14fe6be68e400b4c2b1c5e#diff-e8b1625ba9f60b2fa818f7a704fccae1a7e7bbc696686423677f7cb36b057265R354-R359

**Comment by pdt256** [comment]
Please reopen if there are any further concerns.
